// Code generated by Torpedo DO NOT EDIT.

// Package trip The user fly trip reservations
package trip

import "errors"

var (

	// ErrInvalidField the given field is invalid
	ErrInvalidField = errors.New("the given field is invalid")
)
