// Code generated by Torpedo DO NOT EDIT.

// Package user The user system
package user

import "github.com/darksubmarine/torpedo-lib-go"

// newID returns an ID string representation based on the yaml configuration: UUID or ULID
func newID() string {
	return torpedo_lib.Ulid()
}
