// Code generated by Torpedo DO NOT EDIT.

// Package user The user system
package user

import (
	"github.com/darksubmarine/torpedo-lib-go"
	"github.com/darksubmarine/torpedo-lib-go/entity"
	"github.com/darksubmarine/torpedo-lib-go/tql"
)

var _qroFieldsMap = map[string]string{
	"id":      "Id_",
	"created": "Created_",
	"updated": "Updated_",

	"name": "Name_",

	"email": "Email_",

	"password": "Password_",

	"plan": "Plan_",

	"miles": "Miles_",
}

type EntityQRO struct {
	Id_      *string `json:"id,omitempty"`
	Created_ *int64  `json:"created,omitempty"`
	Updated_ *int64  `json:"updated,omitempty"`

	Name_ *string `json:"name,omitempty"`

	Email_ *string `json:"email,omitempty"`

	Password_ *string `json:"password,omitempty"`

	Plan_ *string `json:"plan,omitempty"`

	Miles_ *int64 `json:"miles,omitempty"`

	QRO
}

func (qro *EntityQRO) FieldValue(field string) interface{} {
	return tql.FieldValue(qro, entity.FieldNameToCode(field))
}

func (qro *EntityQRO) HydrateFromEntity(ety *UserEntity, fields ...string) error {

	if ety == nil {
		return torpedo_lib.ErrNilEntity
	}

	entity.To(ety, qro, fields...)

	return nil
}
