// Code generated by Torpedo DO NOT EDIT.

// Package user The user system
package user

import (
	"github.com/darksubmarine/torpedo-lib-go/context"
	"github.com/darksubmarine/torpedo-lib-go/tql"
)

// IEntityDMO interface to defines the Data Mapper Object implementation
type IEntityDMO interface {
	ToEntity() (*UserEntity, error)
	HydrateFromEntity(entity *UserEntity) error
	Id() string
	Created() int64
	Updated() int64
	Name() string
	Email() string
	Password() (string, error)
	Plan() string
	Miles() int64
}

// IEntityDTO interface to defines the Data Transfer Object implementation
type IEntityDTO interface {
	Id() string
	Created() int64
	Updated() int64

	Name() string
	Email() string
	Password() string
	Plan() string
	Miles() int64
}

// IRepositoryBase interface to defines the base repository implementation
type IRepositoryBase interface {
	Save(entity *UserEntity) error
	FetchByID(id string) (*UserEntity, error)
	Update(entity *UserEntity) error
	DeleteByID(id string) error

	Query(q *tql.Query, metadata map[string]string) ([]*UserEntity, error)
}

// IServiceBase interface to defines the service basis implementation
type IServiceBase interface {
	Create(ctx context.IDataMap, entity *UserEntity) (*UserEntity, error)
	Read(ctx context.IDataMap, id string) (*UserEntity, error)
	Update(ctx context.IDataMap, entity *UserEntity) (*UserEntity, error)
	Delete(ctx context.IDataMap, id string) error
	Query(q *tql.Query) (*tql.Result, error)
}
