// Code generated by Torpedo DO NOT EDIT.

// Package user The user system
package user

import "errors"

var (

	// ErrInvalidField the given field is invalid
	ErrInvalidField = errors.New("the given field is invalid")

	// ErrInvalidPlan the given plan field is invalid
	ErrInvalidPlan = errors.New("the given plan field is invalid")
)
