// Code generated by Torpedo DO NOT EDIT.

// Package mocks the service base trip.ServiceBase for testing purpose
package mocks

import (
	"github.com/darksubmarine/booking-fly/domain/entities/trip"
	"github.com/darksubmarine/torpedo-lib-go/context"
	"github.com/darksubmarine/torpedo-lib-go/tql"
)

type ServiceBase struct {
	Create_ func(ctx context.IDataMap, ety *trip.TripEntity) (*trip.TripEntity, error)
	Read_   func(ctx context.IDataMap, id string) (*trip.TripEntity, error)
	Update_ func(ctx context.IDataMap, ety *trip.TripEntity) (*trip.TripEntity, error)
	Delete_ func(ctx context.IDataMap, id string) error
	Query_  func(q *tql.Query) (*tql.Result, error)

	BelongsToUser_ func(userId string, items int64, page int64) ([]*trip.TripEntity, error)
	DeleteByUser_  func(userId string) error
}

// Create given a new entity this one is populated with ID and creation timestamp and finally saved into the repository
func (s *ServiceBase) Create(ctx context.IDataMap, ety *trip.TripEntity) (*trip.TripEntity, error) {
	return s.Create_(ctx, ety)
}

// Read returns a pointer to TripEntity given its id
func (s *ServiceBase) Read(ctx context.IDataMap, id string) (*trip.TripEntity, error) {
	return s.Read_(ctx, id)
}

// Update returns a pointer to TripEntity after update it
func (s *ServiceBase) Update(ctx context.IDataMap, ety *trip.TripEntity) (*trip.TripEntity, error) {
	return s.Update_(ctx, ety)
}

// Delete removes the entity given its id
func (s *ServiceBase) Delete(ctx context.IDataMap, id string) error {
	return s.Delete_(ctx, id)
}

// Query executes the given query (TQL) and returns the query result
func (s *ServiceBase) Query(q *tql.Query) (*tql.Result, error) {
	return s.Query_(q)
}

// BelongsToUser fetch a list of TripEntity that belongs to User given the userId
func (s *ServiceBase) BelongsToUser(userId string, items int64, page int64) ([]*trip.TripEntity, error) {
	return s.BelongsToUser_(userId, items, page)
}

// DeleteByUser remove all trip given the userId
func (s *ServiceBase) DeleteByUser(userId string) error {
	return s.DeleteByUser_(userId)
}
