// Code generated by Torpedo DO NOT EDIT.

// Package booking_fly Fly reservation use case

package booking_fly

import (
	"github.com/darksubmarine/torpedo-lib-go/log"

	"github.com/darksubmarine/booking-fly/domain/entities/user"

	"github.com/darksubmarine/booking-fly/domain/entities/trip"
)

type UseCaseBase struct {
	logger log.ILogger

	userSrv user.IService

	tripSrv trip.IService
}

func NewUseCaseBase(logger log.ILogger, userSrv user.IService, tripSrv trip.IService) *UseCaseBase {
	return &UseCaseBase{logger: logger,
		userSrv: userSrv, tripSrv: tripSrv,
	}
}
