// Code generated by TORPEDO DO NOT EDIT.

// Package mongodb is an output adapter to store entities in MongoDB
package mongodb

import (
	"github.com/darksubmarine/booking-fly/domain/entities/user"
	"github.com/darksubmarine/torpedo-lib-go/entity"
	"github.com/darksubmarine/torpedo-lib-go/storage/mongodb_utils"
	"go.mongodb.org/mongo-driver/bson"
)

// EntityDMOMongoDB Data Mapper Object (DMO) to store entity into MongoDB
type EntityDMOMongoDB struct {
	*user.EntityDMO `bson:"-"`

	Id_      string `bson:"_id"`
	Created_ int64  `bson:"created"`
	Updated_ int64  `bson:"updated"`

	Name_     string `bson:"name" `
	Email_    string `bson:"email" `
	Password_ string `bson:"password" torpedo.field:"encrypted"`
	Plan_     string `bson:"plan" `
	Miles_    int64  `bson:"miles" `

	DMO `bson:"inline"`
}

// NewEntityDMOMongoDB constructor function
//
//	 params:
//			- key []byte is the encryption key for the encrypted fields
func NewEntityDMOMongoDB(key []byte) *EntityDMOMongoDB {
	dmo := new(EntityDMOMongoDB)
	dmo.EntityDMO = user.NewEntityDMO(key)
	dmo.DMO.EntityDMO = dmo.EntityDMO // TODO review this line. It is to support encryption at custom DMO
	return dmo
}

// NewEntityDMOMongoDBFrom DMO constructor function from a given user.UserEntity.
//
//	 params:
//			- ety: *user.UserEntity entity from the DMO will be created
//			- key: []byte is the encryption key for the encrypted fields
func NewEntityDMOMongoDBFrom(ety *user.UserEntity, key []byte) (*EntityDMOMongoDB, error) {
	d := NewEntityDMOMongoDB(key)
	if err := entity.To(ety, d); err != nil {
		return nil, err
	}
	return d, nil
}

// Id getter method
func (dmo *EntityDMOMongoDB) Id() string { return dmo.Id_ }

// Created getter method
func (dmo *EntityDMOMongoDB) Created() int64 { return dmo.Created_ }

// Updated getter method
func (dmo *EntityDMOMongoDB) Updated() int64 { return dmo.Updated_ }

// Name getter method
func (dmo *EntityDMOMongoDB) Name() string { return dmo.Name_ }

// Email getter method
func (dmo *EntityDMOMongoDB) Email() string { return dmo.Email_ }

// Password getter method
func (dmo *EntityDMOMongoDB) Password() (string, error) {
	return dmo.DecryptString(dmo.Password_)
}

// Plan getter method
func (dmo *EntityDMOMongoDB) Plan() string { return dmo.Plan_ }

// Miles getter method
func (dmo *EntityDMOMongoDB) Miles() int64 { return dmo.Miles_ }

// ToEntity returns a user.UserEntity from the DMO object
func (dmo *EntityDMOMongoDB) ToEntity() (*user.UserEntity, error) {
	ety := user.New()
	if err := entity.From(dmo, ety); err != nil {
		return nil, err
	}
	return ety, nil
}

// HydrateFromEntity populates the DMO fields from the user.UserEntity
func (dmo *EntityDMOMongoDB) HydrateFromEntity(ety *user.UserEntity) error {
	return entity.To(ety, dmo)
}

// updateDocument mapper function from DMO to bson.D to update document into the mongoDB collection
func (dmo *EntityDMOMongoDB) updateDocument(metadata map[string]*entity.FieldMetadata) bson.D {
	bsonD := mongodb_utils.ToBSONDocument(dmo, metadata, "Id_", "Created_")
	return bson.D{{"$set", bsonD}}
}
