// Code generated by Torpedo DO NOT EDIT.

// Package mocks the service base domain. ServiceBase for testing purpose
package mocks

import (
	"github.com/darksubmarine/booking-fly/domain"
	"github.com/darksubmarine/booking-fly/domain/entities/trip"
	"github.com/darksubmarine/booking-fly/domain/entities/user"
)

type ServiceBase struct {
	Context_ func() *domain.Context

	Trip_ func() trip.IService
	User_ func() user.IService
}

func (s *ServiceBase) Context() *domain.Context { return s.Context_() }

func (s *ServiceBase) Trip() trip.IService { return s.Trip_() }

func (s *ServiceBase) User() user.IService { return s.User_() }
